/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com2002ug25;

/**
 *
 * @author aca12pim
 */
public class Healthplan extends javax.swing.JFrame {

    /**
     * Creates new form Healthplan
     */
    public Healthplan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plan = new javax.swing.ButtonGroup();
        planNone = new javax.swing.JRadioButton();
        planNHS = new javax.swing.JRadioButton();
        planMainenance = new javax.swing.JRadioButton();
        planOralHealth = new javax.swing.JRadioButton();
        planDentalRepair = new javax.swing.JRadioButton();
        newPlan = new javax.swing.JRadioButton();
        newPlanName = new javax.swing.JTextField();
        newPlanCost = new javax.swing.JTextField();
        newPlanNameLabel = new javax.swing.JLabel();
        newPlanCostLabel = new javax.swing.JLabel();
        costPerMonthLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Healthplans");

        plan.add(planNone);
        planNone.setText("None");
        planNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planNoneActionPerformed(evt);
            }
        });

        plan.add(planNHS);
        planNHS.setText("NHS (Under 18 Only) £0");
        planNHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planNHSActionPerformed(evt);
            }
        });

        plan.add(planMainenance);
        planMainenance.setText("Maintenance Plan £15 per month");

        plan.add(planOralHealth);
        planOralHealth.setText("Oral Health Plan £21 per month");

        plan.add(planDentalRepair);
        planDentalRepair.setText("Dental Repair Plan £36 per month");

        plan.add(newPlan);
        newPlan.setText("New plan:");
        newPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPlanActionPerformed(evt);
            }
        });

        newPlanNameLabel.setText("Name");

        newPlanCostLabel.setText("Cost");

        costPerMonthLabel.setText("per month");

        confirmButton.setText("Confirm");

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planNone)
                    .addComponent(planNHS)
                    .addComponent(planMainenance)
                    .addComponent(planOralHealth)
                    .addComponent(planDentalRepair)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(newPlanCostLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newPlanCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costPerMonthLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newPlanNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newPlanName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planNone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planNHS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planMainenance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planOralHealth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planDentalRepair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPlan)
                    .addComponent(newPlanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPlanNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPlanCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPlanCostLabel)
                    .addComponent(costPerMonthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void planNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planNoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planNoneActionPerformed

    private void planNHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planNHSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planNHSActionPerformed

    private void newPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Healthplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Healthplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Healthplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Healthplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Healthplan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel costPerMonthLabel;
    private javax.swing.JRadioButton newPlan;
    private javax.swing.JTextField newPlanCost;
    private javax.swing.JLabel newPlanCostLabel;
    private javax.swing.JTextField newPlanName;
    private javax.swing.JLabel newPlanNameLabel;
    private javax.swing.ButtonGroup plan;
    private javax.swing.JRadioButton planDentalRepair;
    private javax.swing.JRadioButton planMainenance;
    private javax.swing.JRadioButton planNHS;
    private javax.swing.JRadioButton planNone;
    private javax.swing.JRadioButton planOralHealth;
    // End of variables declaration//GEN-END:variables
}
